[project]
name = "mcp-finance-api-server"
version = "0.1.0"
description = "yfinance module MCP Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.5.1",
    "yfinance>=0.2.61",
]
